# Site settings
title_left: "Tuna"
title_right: "Space" # default: ""
description: "Just a minimal blog where I can take notes about my daily life."
keywords: "tuna, tunadate, blog, development, minimalist"
domain: tuna-date.github.io/
url: https://tuna-date.github.io/ # site url
baseurl: "" # apply repo name like "/myproject" if used under gh-pages branch, else (under master branch) just leave empty/blank
cover: "" # image uri like logo/cover image for site seo
repository: tuna-date/tuna-date.github.io

google_analytics: UA-XXXXX-XX
twitter_username: ""
comments_enabled: true # if enabled (set to true), please provide your disqus_username
disqus_shortname: "tuna"
postshare_enabled: true

# Build settings
permalink: /:year/:title/
markdown: kramdown
highlighter: rouge

source: ./
destination: ./docs

# Sass configuration
sass:
  sass_dir: assets/scss
  style: compressed # expanded

# Author settings
author:
  name: "Tu Nguyen"

plugins:
  - jekyll-sitemap
  - bourbon
  - jekyll-paginate

# navbar pages
navbar:
  - slug: about
    title: About
  - slug: blog
    title: Blog

exclude:
  - "gulp"
  - "node_modules"
  - "bower"
  - "bower_components"
  - "config.rb"
  - "src"
  - "Gemfile"
  - "Gemfile.lock"
  - ".rvmrc"
  - ".rbenv-version"
  - "package.json"
  - "gulpfile.js"
  - "README.md"
  - "Rakefile"
  - "changelog.md"
  - "script"
  - "vendor"
  - "thinkspace.gemspec"
